name: Run Unit Tests In Any Push

on:
  workflow_call:
    inputs:
      docker-compose:
        required: false
        type: string
        default: ''
      lint:
        required: false
        type: boolean
        default: false
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pipenv'
      - name: Install Pip and Pipenv
        run: |
          python -m pip install --upgrade pip pipenv==2022.8.5
          pipenv sync --dev
      - name: Linter (Black)
        if: inputs.lint != ''
        run: ./lint.sh --check
      - name: Docker Compose UP
        if: inputs.docker-compose != ''
        run: docker-compose up -d  ${{ inputs.docker-compose }}
      - name: Run Unit Tests
        run: |
          sleep 10
          PYTHONPATH=. pipenv run coverage run -m pytest
