name: Run Unit Tests In Any Push

on:
  workflow_call:
    inputs:
      docker-compose:
        required: false
        type: string
        default: ''
      lint:
        required: false
        type: boolean
        default: false
      python-version:
        type: string
        default: '3.9'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          cache: 'pipenv'
      - name: Install Pip and Pipenv
        run: |
          python -m pip install --upgrade pip==23.1.2 pipenv==2023.5.19
          pipenv sync --dev
      - name: Linter (Black)
        if: inputs.lint != ''
        run: ./lint.sh --check
      - name: Docker Compose UP
        if: inputs.docker-compose != ''
        run: | 
          docker-compose up -d  ${{ inputs.docker-compose }}
          sleep 10
      - name: Run Unit Tests
        run: |
          PYTHONPATH=. pipenv run coverage run -m pytest
