name: Run Unit Tests In Any Push

on:
  workflow_call:
    inputs:
      docker-compose:
        required: false
        type: string
        default: ''
        description: 'list of compose services separated by space'
      black:
        required: false
        type: boolean
        default: false
      autoflake:
        required: false
        type: boolean
        default: false
      mypy:
        required: false
        type: boolean
        default: false
      python-version:
        type: string
        default: '3.9'
      project-path:
        type: string
        default: src
        description: Main project path containing python source code that will be in production
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pipenv'
      - name: Install Pip and Pipenv
        run: |
          python -m pip install --upgrade pip==23.1.2 pipenv==2023.5.19
          pipenv sync --dev

      - name: Linter (Black)
        if: inputs.black
        run: pipenv run black --check --diff ${{ inputs.project-path }}

      - name: Linter (Autoflake)
        if: inputs.autoflake
        run: pipenv run autoflake -cr ${{ inputs.project-path }}

      - name: Linter (MyPy)
        if: inputs.mypy
        run: pipenv run mypy ${{ inputs.project-path }}

      - name: Docker Compose UP
        if: inputs.docker-compose != ''
        run: |
          docker-compose up -d  ${{ inputs.docker-compose }}
          sleep 10
      - name: Run Unit Tests
        run: |
          PYTHONPATH=. pipenv run coverage run -m pytest
